Release Tracking
primer/eslint-plugin-primer-react pull request #264
Opened 2024-10-24 11:12 UTC by primer-css

This PR was opened by the [Changesets release](https://github.com/changesets/action) GitHub action. When you're ready to do a release, you can merge this and the packages will be published to npm automatically. If you're not ready to do a release yet, that's fine, whenever you add more changesets to main, this PR will be updated.

# Releases
## eslint-plugin-primer-react@6.2.0

### Minor Changes

-   [#258](https://github.com/primer/eslint-plugin-primer-react/pull/258) [`83f29f3`](https://github.com/primer/eslint-plugin-primer-react/commit/83f29f339999b9c21d95167bcc2680c1797cbab6) Thanks [@keithamus](https://github.com/keithamus)! - Add enforce-css-module-identifier-casing rule

2024-10-25 16:51 UTC, jonrohan approved these changes

2024-10-25 17:50 UTC, keithamus requested changes
I'd like us to integrate this into dotcom for extra validation before release, so I'm just putting a block on this until we do that.

2024-11-15 02:37 UTC, broccolinisoup commented
Please make sure to update the rule name (`a11y-use-next-tooltip` -> `a11y-use-accessible-tooltip`) at dotcom when bumping the version 🙏🏻

2025-04-23 13:45 UTC, francinelucca approved these changes

2025-04-23 14:16 UTC, merged